### ISSUE TITLE
same branch create for different target branches

### ISSUE THREAD

**Issue by Ginxo** [gorillio/github-action-cherry-pick#1]
Hi, first of all, congrats for your very helpful tool. 
I've found some weird behavior (may be is my fault), the thing is [when I apply matrix strategy](https://github.com/kiegroup/github-action-build-chain/blob/master/.github/workflows/update_branches.yml) to create a PR for every branch I want to propagate changes the PRs are created properly but from the same source branch.
See the example:

- https://github.com/kiegroup/github-action-build-chain/pull/44
- https://github.com/kiegroup/github-action-build-chain/pull/45
- https://github.com/kiegroup/github-action-build-chain/pull/46

So in case I have to resolve conflicts the merge commit is produced over the same branch for all them which produces more conflicts over the different PRs.

Did I explain myself well? :thinking: 

Thanks!

**Comment by himadrisingh** [comment]
ok, need to test out for multiple branches.

**Comment by Ginxo** [comment]
thanks man! @himadrisingh looking forward to your input! :wink:

**Comment by Borda** [comment]
I guess that the solution would be using target branch name and short SHA in the PR branch name so each would be unique
